### ISSUE TITLE
is_encrypted() test on unencrypted XLS file throws TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by nuclearpidgeon** [nolze/msoffcrypto-tool#15]
When trying to test for encryption on an unencrypted Excel 97-2003 file:

```
stewartwebb@shrinkpad:~/Documents$ msoffcrypto-tool -t ./test.xls 
Traceback (most recent call last):
  File "/home/stewartwebb/.virtualenvs/venv/bin/msoffcrypto-tool", line 11, in <module>
    sys.exit(main())
  File "/home/stewartwebb/.virtualenvs/venv/local/lib/python2.7/site-packages/msoffcrypto/__main__.py", line 50, in main
    if not is_encrypted(args.infile):
  File "/home/stewartwebb/.virtualenvs/venv/local/lib/python2.7/site-packages/msoffcrypto/__main__.py", line 34, in is_encrypted
    return file.is_encrypted()
  File "/home/stewartwebb/.virtualenvs/venv/local/lib/python2.7/site-packages/msoffcrypto/format/xls97.py", line 583, in is_encrypted
    num, size = workbook.skip_to(47)
TypeError: 'NoneType' object is not iterable
stewartwebb@shrinkpad:~/Documents$ 
```

I was able to reproduce this by making a new spreadsheet in OpenOffice Calc, putting some random text in a few cells in all three default sheets, the saving and exporting as an Excel 97/2003 file (.xls).

Can't seem to see what would be causing that error - would it be anything to do with me running Python 2?

**Comment by nolze** [comment]
Thank you for reporting!

It was caused by implementation bugs. It should be fixed in PR #16 and so v4.6.2.
