### ISSUE TITLE
In-memory example

### ISSUE THREAD

**Issue by cvanhoutte** [nolze/msoffcrypto-tool#58]
Hi there

Thanks for your work on this package. I've had success using your cli tool and as a library, but the 'in-memory' example doesn't work for me.

`>>> df = pd.read_excel(decrypted)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda/lib/python3.5/site-packages/pandas/io/excel.py", line 170, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/Users/user/anaconda/lib/python3.5/site-packages/pandas/io/excel.py", line 225, in __init__
    self.book = xlrd.open_workbook(file_contents=data)
  File "/Users/user/anaconda/lib/python3.5/site-packages/xlrd/__init__.py", line 395, in open_workbook
    with open(filename, "rb") as f:
TypeError: invalid file: None`

Unfortunately I can't share the file for testing, other than to say it is working fine for the other methods. I can't see where this aspect of the package is getting tested. Do you have any suggestions?

Thanks

**Comment by nolze** [comment]
As you observed, `msoffcrypto-tool` looks fine there. I guess you're using an outdate version of `xlrd` and suggest you update it to the latest version. (Also note that we no longer support Python 3.5 officially)
