### ISSUE TITLE
Problem using msoffcrypto after unzipping a file in python

### ISSUE THREAD

**Issue by Ludo915** [nolze/msoffcrypto-tool#66]
Hello,

I am unzipping excel files and then trying to open them to store them in dataframes but I get a permission error that makes me think I am not closing something properly any ideas? Here is a sample of the code:

```
def mistubishi_password(self, password, x, attachments):
        for att in attachments:
            with ZipFile(self.DIR_SBD + att.FileName) as zipObj:
                listOfFileNames = zipObj.namelist()
                print(listOfFileNames)
                for file in listOfFileNames:
                    file_extension = file.split(".")[1]

                    if file_extension.lower() == "xls":
                        if(("[Trial Balance_JPY]" in file) | ("[Traditional Fund Structure NAV]" in file)):
                            goodfile = file
                            zipObj.extract(goodfile, path = self.DIR_SBD + goodfile, pwd=password.encode())


                if("[Trial Balance_JPY]" in goodfile):
                    zipObj.close()
                    protfile = msoffcrypto.OfficeFile(open(self.DIR_SBD + goodfile, "rb"))
                    protfile.load_key(password=password)
                    decrypted = io.BytesIO()
                    protfile.decrypt(decrypted)
                    df = pd.read_excel(decrypted)
                    print(df)
    return None
```

Here is the error message I am getting:

```
July 29, 2021 NAV - MY-AMD Global Multi Asset Fund 1327014 [PW]
 15%|█▌        | 88/584 [00:43<02:21,  3.50it/s]['[Traditional Fund Structure NAV] [1327014].pdf', '[Traditional Fund Structure NAV] [1327014].xls']
 15%|█▌        | 88/584 [00:43<04:07,  2.01it/s]
Traceback (most recent call last):
  File "C:/Users/giraudl/PycharmProjects/Automatization_PDP/main.py", line 501, in <module>
    GestionBoitePDP.get_mail_print_to_csv()
  File "C:/Users/giraudl/PycharmProjects/Automatization_PDP/main.py", line 483, in get_mail_print_to_csv
    self.mistubishi_password(self.password_1327014, x, attachments)
  File "C:/Users/giraudl/PycharmProjects/Automatization_PDP/main.py", line 110, in mistubishi_password
    file = msoffcrypto.OfficeFile(open(self.DIR_SBD + goodfile, "rb"))
PermissionError: [Errno 13] Permission denied: 'C:/Users/giraudl/PycharmProjects/Automatization_PDP/attachments/[Traditional Fund Structure NAV] [1327014].xls

```

**Comment by nolze** [comment]
I think it may have nothing to do with `msoffcrypto-tool`.

Possibly, you should write

```
zipObj.extract(goodfile, path = self.DIR_SBD, pwd=password.encode())
```

instead of

```
zipObj.extract(goodfile, path = self.DIR_SBD + goodfile, pwd=password.encode())
```

(see <https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extract>)

**Comment by Ludo915** [comment]
Yes Thank you nolze, this solved the issue.

Kind regards.

Ludo
