### ISSUE TITLE
Error Unrecognized file format

### ISSUE THREAD

**Issue by adrastee** [nolze/msoffcrypto-tool#8]
Hello,
Installed using pip on ubutun:
```
root@Laptop:~# python /usr/local/bin/msoffcrypto-tool -p passwd xxx.xls out.xls
Traceback (most recent call last):
  File "/usr/local/bin/msoffcrypto-tool", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/msoffcrypto/__main__.py", line 67, in main
    file = OfficeFile(args.infile)
  File "/usr/local/lib/python2.7/dist-packages/msoffcrypto/__init__.py", line 30, in OfficeFile
    raise AssertionError("Unrecognized file format")
AssertionError: Unrecognized file format
```
Thanks for your help!

**Comment by adrastee** [comment]
Ok! Thanks for the link. So I'll wait for the next release :)

**Comment by nolze** [comment]
FYI: I implemented [experimental support for .xls files](https://github.com/nolze/msoffcrypto-tool/pull/10) today.

I cannot assure you it works, but I think it's worth a try 👍

**Comment by adrastee** [comment]
It works great! Thanks a lot!
